Essential project files
Phoenix-Protocol-Group/phoenix-frontend pull request #2
Opened 2023-06-14 09:20 UTC by VarNotUsed

2023-06-15 11:12 UTC, WYNerD commented on packages/core/README.md
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
Why did you put the gitignore stuff into a readme?

2023-06-15 11:13 UTC, msteiner96 requested changes

2023-06-15 11:13 UTC, msteiner96 commented on packages/core/README.md
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
This shouldn't be in a README file.

2023-06-23 09:45 UTC, msteiner96 approved these changes

2023-06-23 09:45 UTC, merged